name = "DLPack"
uuid = "53c2dc0f-f7d5-43fd-8906-6c0220547083"
authors = ["Pablo Zubieta"]
version = "0.1.2"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
CUDA = "â‰¥ 1.3"
PyCall = "1.92"
PythonCall = "0.6.1"
Requires = "1.3"
julia = "1.3"

[extras]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
